spring:
  datasource:
    driverClassName: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/postgres
    username: root
    password: root
  jooq:
    sql-dialect: POSTGRES
  flyway:
    locations: db/migration